Use MIMC hashing function instead of SHA256
ConsenSys/orchestrate-hashicorp-vault-plugin pull request #23
Opened 2021-04-16 13:57 UTC by darioAnongba

Use MIMC hashing function instead of SHA256

2021-04-16 14:05 UTC, julien-marchand requested changes
@darioAnongba looks good to me.

I'd like also to address the concern about the encoding of input:
"The API takes a “string” as data, I think the API should specify an encoding (hexadecimal?). Currently, according to my rudimentary unit tests, if I give something like 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824as data, under the hood you cast it as []byte which will lead to errors one way or another."
WDYT?

2021-04-16 14:10 UTC, darioAnongba commented
@julien-marchand yes I asked Gautam what he meant by that because I'm not sure I understood, I can change that in a next MR waiting for him to anwer.

2021-04-19 13:09 UTC, julien-marchand approved these changes

2021-04-19 13:09 UTC, Kriys94 approved these changes

2021-04-19 14:48 UTC, merged